#!/usr/bin/env tsx
/**
 * Regenerate src/lib/tool-catalog.generated.ts from the MCP tool registry.
 *
 *   npm run catalog:sync           # rewrite the file in place
 *   npm run catalog:sync -- --check  # exit 1 if it would change (CI gate)
 *
 * Why a build-time generated file rather than a runtime tRPC introspection?
 * Next.js (Webpack/Turbopack) cannot resolve the `.js` extensions used by
 * MCP modules' NodeNext-style imports, so importing the registry from a
 * Next.js process fails at module-resolution time. tsx handles those
 * extensions natively, so we run the registry walk in a Node script and
 * persist the result as plain TypeScript that Next.js can import directly.
 *
 * The catalog is static at build time — tools never register at runtime —
 * so a generated file is structurally correct, not a workaround.
 */

import { readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Populate the registry by importing every tool module. Order matches
// src/mcp/server.ts so the generated catalog mirrors what the MCP server
// actually exposes.
import "../src/mcp/extended-tools.js";
import "../src/mcp/tools/claim-tools.js";
import "../src/mcp/tools/context-tools.js";
import "../src/mcp/tools/decision-tools.js";
import "../src/mcp/tools/discovery-tools.js";
import "../src/mcp/tools/doctor-tools.js";
import "../src/mcp/tools/fact-tools.js";
import "../src/mcp/tools/git-tools.js";
import "../src/mcp/tools/instrumentation-tools.js";
import "../src/mcp/tools/knowledge-tools.js";
import "../src/mcp/tools/onboarding-tools.js";
import "../src/mcp/tools/plan-card.js";
import "../src/mcp/tools/query-tools.js";
import "../src/mcp/tools/relation-tools.js";
import "../src/mcp/tools/session-tools.js";
import "../src/mcp/tools/status-tools.js";
import "../src/mcp/tools/summary-tools.js";
import "../src/mcp/tools/tag-tools.js";
import "../src/mcp/tools/token-tools.js";

import { ESSENTIAL_TOOLS } from "../src/mcp/manifest.js";
import { getAllExtendedTools, getToolCatalog } from "../src/mcp/tool-registry.js";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..");
const OUTPUT = resolve(REPO_ROOT, "src/lib/tool-catalog.generated.ts");

function buildCatalog() {
	const extended = getAllExtendedTools();
	const schemas: Record<string, Record<string, unknown>> = {};
	for (const tool of extended) {
		const detail = getToolCatalog({ tool: tool.name });
		if (detail?.type === "detail") {
			schemas[tool.name] = detail.tool.parameters;
		}
	}
	return { essentials: ESSENTIAL_TOOLS, extended, schemas };
}

function render(): string {
	const catalog = buildCatalog();
	return `// AUTO-GENERATED by scripts/sync-tool-catalog.ts — do not edit.
// Run \`npm run catalog:sync\` after changing MCP tool registrations.

import type { ToolParamInfo } from "@/lib/mcp-types";

export type EssentialTool = { name: string; description: string };
export type ExtendedTool = {
\tname: string;
\tcategory: string;
\tdescription: string;
\treadOnly: boolean;
\tdestructive: boolean;
};

export const TOOL_CATALOG: {
\tessentials: EssentialTool[];
\textended: ExtendedTool[];
\tschemas: Record<string, Record<string, ToolParamInfo>>;
} = ${JSON.stringify(catalog, null, "\t")};
`;
}

async function main() {
	const check = process.argv.includes("--check");
	const next = render();
	const rel = relative(REPO_ROOT, OUTPUT);

	let original: string | null = null;
	try {
		original = await readFile(OUTPUT, "utf8");
	} catch {
		// File doesn't exist yet — treat as drift.
	}

	if (original === next) {
		console.log(`✓ ${rel} is up to date`);
		return;
	}

	if (check) {
		console.error(`✗ ${rel} is out of date — run \`npm run catalog:sync\``);
		process.exit(1);
	}

	await writeFile(OUTPUT, next);
	console.log(`✓ regenerated ${rel}`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
